version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:9091
    volumes:
      - .:/app
    ports:
      - "9091:9091"
    env_file:
      - .env